version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: flamesentinels-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: flamesentinels
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - flamesentinels-network

  mongo-express:
    image: mongo-express
    container_name: flamesentinels-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    networks:
      - flamesentinels-network

volumes:
  mongodb_data:

networks:
  flamesentinels-network:
    driver: bridge 